### ISSUE TITLE
Simpler way to create invites

### ISSUE THREAD

**Issue by timjrobinson** [ahdinosaur/ssb-pub#7]
I just created a new pub using the docker container on my server, however it took ~2 minutes for ssb to start for some reason (still unsure why). 

I noticed the command to create invites in the README basically spawns a new container just to run the invite.create command, and this doesn't work for me because the sbot server hasn't started yet. I get the following:

```
Error: Could not connect to the scuttlebot server.
Use the "server" command to start it.
```

I discovered there's a much simpler way to create invites. With the following:
```
docker exec -it sbot sbot invite.create 1     
```
My docker container is called `sbot`, This is just executing the command `sbot invite.create 1` inside of it. It might make sense to add this to the README.

**Comment by cryptix** [comment]
Interesting.. I also installed this pub and it replicates fine (using an established key) but I can't interact with it. Execing into it and running sbot commands, it just stalls, also whoami.

But I also see a lot of the [Error: wrong number](https://github.com/ssbc/scuttlebot/issues/380#issuecomment-374614099) errors with this installation but not from localhost so I don't think that's the proble... Good to hear that it _should_ work, since I thought docker should contain differences away....
